import Head from 'next/head'
import { Inter } from '@next/font/google'
import Sidebar from '../components/Sidebar'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Chat App</title>
        <meta name="description" content="Generated by Long" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Sidebar />
    </>
  )
}
